name: Publish package to npm

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      bump:
        required: true
        description: 'Release Type'
        type: choice
        default: 'patch'
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Configure Git
        run: |
          git config --local user.name 'Temporal Data (cicd)'
          git config --local user.email 'commander-data@temporal.io'
      - name: Bump version
        run: npm version --no-commit-hooks ${{ inputs.bump }}
      - name: Create Pull Request
        run: ./.github/scripts/bump-version.sh
        env:
          GITHUB_TOKEN: ${{ secrets.COMMANDER_DATA_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
