name: Publish NPM Package

on:
  pull_request:
    branches:
      - 'releases/**'

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: echo '${{ toJSON(github) }}'
  publish:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Checkout Release Tag
        run: |
          git fetch --tags
          tag=`git describe --abbrev=0 --tags`
          git checkout $tag
      - name: Install dependencies
        run: pnpm install
      - name: Build Package
        run: pnpm package
      - name: Publish package to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: ./package
  create_release:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Release
        run: |
          git fetch --tags
          tag=`git describe --abbrev=0 --tags`
          gh release create $tag --generate-notes
        env:
          GH_TOKEN: ${{ secrets.TEMPORAL_UI_TOKEN }}
